// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAVK-DtyVxwWL6fB4O8oxaqWmDptLlZ8A0",
    authDomain: "elevate-360-5f40b.firebaseapp.com",
    projectId: "elevate-360-5f40b",
    storageBucket: "elevate-360-5f40b.firebasestorage.app",
    messagingSenderId: "1063730194040",
    appId: "1:1063730194040:web:5bbd4bb0e9d9ac13632f8d",
    measurementId: "G-9DZ61NM6JB",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAVK-DtyVxwWL6fB4O8oxaqWmDptLlZ8A0",
    authDomain: "elevate-360-5f40b.firebaseapp.com",
    projectId: "elevate-360-5f40b",
    storageBucket: "elevate-360-5f40b.firebasestorage.app",
    messagingSenderId: "1063730194040",
    appId: "1:1063730194040:android:7ed3bf2d007d78dd632f8d",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAVK-DtyVxwWL6fB4O8oxaqWmDptLlZ8A0",
    authDomain: "elevate-360-5f40b.firebaseapp.com",
    projectId: "elevate-360-5f40b",
    storageBucket: "elevate-360-5f40b.firebasestorage.app",
    messagingSenderId: "1063730194040",
    appId: "1:1063730194040:ios:your-ios-app-id",
    iosBundleId: "com.elevate360.elevate360",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAVK-DtyVxwWL6fB4O8oxaqWmDptLlZ8A0",
    authDomain: "elevate-360-5f40b.firebaseapp.com",
    projectId: "elevate-360-5f40b",
    storageBucket: "elevate-360-5f40b.firebasestorage.app",
    messagingSenderId: "1063730194040",
    appId: "1:1063730194040:macos:your-macos-app-id",
    iosBundleId: "com.elevate360.elevate360",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAVK-DtyVxwWL6fB4O8oxaqWmDptLlZ8A0",
    authDomain: "elevate-360-5f40b.firebaseapp.com",
    projectId: "elevate-360-5f40b",
    storageBucket: "elevate-360-5f40b.firebasestorage.app",
    messagingSenderId: "1063730194040",
    appId: "1:1063730194040:windows:your-windows-app-id",
  );
}
