import 'package:flutter/material.dart';
import '../models/user_model.dart';
import '../models/goal_model.dart';
import '../services/goal_service.dart';
import '../services/employee_service.dart';
import '../core/utils/app_theme.dart';
import '../core/utils/responsive_utils.dart';

class EmployeeGoalsScreen extends StatefulWidget {
  final UserModel userModel;

  const EmployeeGoalsScreen({
    super.key,
    required this.userModel,
  });

  @override
  State<EmployeeGoalsScreen> createState() => _EmployeeGoalsScreenState();
}

class _EmployeeGoalsScreenState extends State<EmployeeGoalsScreen> {
  String _selectedFilter = 'All';
  final List<String> _filters = ['All', 'Not Started', 'In Progress', 'Completed', 'Overdue'];
  bool _isLoading = true;
  late String _employeeId;
  List<GoalModel> _goals = [];
  List<GoalModel> _availableGoals = [];
  
  @override
  void initState() {
    super.initState();
    _loadEmployeeData();
  }

  Future<void> _loadEmployeeData() async {
    try {
      // Get employee data using user account ID
      final employee = await EmployeeService.getEmployeeByUserAccountId(widget.userModel.uid);
      _employeeId = employee.id;
      
      await _loadGoals();
      await _loadAvailableGoals();
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error loading goals: $e')),
      );
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _loadGoals() async {
    try {
      final goals = await GoalService.getGoalsByEmployeeId(_employeeId);
      setState(() => _goals = goals);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error loading goals: $e')),
      );
    }
  }

  Future<void> _loadAvailableGoals() async {
    try {
      // Get goals that are not assigned to this employee
      final allGoals = await GoalService.getAllGoals();
      setState(() {
        _availableGoals = allGoals.where((goal) => 
          goal.employeeId.isEmpty && // Unassigned goals
          goal.status == 'Not Started' // Only not started goals can be opted in
        ).toList();
      });
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error loading available goals: $e')),
      );
    }
  }

  Future<void> _optInForGoal(GoalModel goal) async {
    try {
      setState(() => _isLoading = true);

      // Create a new goal for the employee based on the template
      final employeeGoal = GoalModel(
        id: '', // Will be generated by Firebase
        employeeId: _employeeId,
        managerId: goal.managerId,
        categoryId: goal.categoryId,
        projectId: goal.projectId,
        title: goal.title,
        description: goal.description,
        goalType: goal.goalType,
        priority: goal.priority,
        weightage: goal.weightage,
        targetValue: goal.targetValue,
        currentValue: 0,
        unit: goal.unit,
        measurementMethod: goal.measurementMethod,
        startDate: DateTime.now(),
        dueDate: goal.dueDate,
        status: 'Not Started',
        progressPercentage: 0,
        isStretchGoal: goal.isStretchGoal,
        createdBy: goal.createdBy,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await GoalService.createGoal(employeeGoal);
      await _loadGoals();
      await _loadAvailableGoals();

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Successfully opted in for the goal')),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error opting in for goal: $e')),
      );
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _updateGoalProgress(GoalModel goal, double progress, String status) async {
    try {
      setState(() => _isLoading = true);

      // Calculate current value based on progress percentage
      final currentValue = goal.targetValue != null 
        ? (goal.targetValue! * progress / 100)
        : progress;

      // Create updated goal model
      final updatedGoal = GoalModel(
        id: goal.id,
        employeeId: goal.employeeId,
        managerId: goal.managerId,
        categoryId: goal.categoryId,
        projectId: goal.projectId,
        title: goal.title,
        description: goal.description,
        goalType: goal.goalType,
        priority: goal.priority,
        weightage: goal.weightage,
        targetValue: goal.targetValue,
        currentValue: currentValue,
        unit: goal.unit,
        measurementMethod: goal.measurementMethod,
        startDate: goal.startDate,
        dueDate: goal.dueDate,
        completionDate: status == 'Completed' ? DateTime.now() : null,
        status: status,
        progressPercentage: progress,
        isStretchGoal: goal.isStretchGoal,
        createdBy: goal.createdBy,
        approvedBy: goal.approvedBy,
        createdAt: goal.createdAt,
        updatedAt: DateTime.now(),
      );

      // Update goal in Firebase
      await GoalService.updateGoal(updatedGoal);
      await _loadGoals(); // Reload goals to update UI

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('Goal updated successfully'),
          backgroundColor: AppTheme.successColor,
          behavior: SnackBarBehavior.floating,
        ),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error updating goal: $e'),
          backgroundColor: AppTheme.errorColor,
          behavior: SnackBarBehavior.floating,
        ),
      );
    } finally {
      setState(() => _isLoading = false);
    }
  }



  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Center(child: CircularProgressIndicator());
    }

    final filteredGoals = _getFilteredGoals();
    
    return ResponsiveUtils.buildResponsiveLayout(
      context: context,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header with stats
          _buildHeader(),
          
          SizedBox(height: ResponsiveUtils.getSectionSpacing(context)),
          
          // Quick stats
          _buildStatsRow(),
          
          SizedBox(height: ResponsiveUtils.getSectionSpacing(context)),
          
          // Filter and search
          _buildFilterSection(),
          
          SizedBox(height: ResponsiveUtils.getSectionSpacing(context)),
          
          // Available Goals Section
          if (_availableGoals.isNotEmpty) ...[
            ResponsiveUtils.buildResponsiveSection(
              context: context,
              title: 'Available Goals',
              icon: Icons.add_task,
              children: [
                GridView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: ResponsiveUtils.getGridCrossAxisCount(
                      context,
                      mobile: 1,
                      tablet: 2,
                      desktop: 3,
                    ),
                    crossAxisSpacing: ResponsiveUtils.getSpacing(context),
                    mainAxisSpacing: ResponsiveUtils.getSpacing(context),
                    childAspectRatio: ResponsiveUtils.isMobile(context) ? 1.2 : 1.5,
                  ),
                  itemCount: _availableGoals.length,
                  itemBuilder: (context, index) {
                    return _buildAvailableGoalCard(_availableGoals[index]);
                  },
                ),
              ],
            ),
            SizedBox(height: ResponsiveUtils.getSectionSpacing(context)),
          ],
          
          // Available Goals Section
          if (_availableGoals.isNotEmpty) ...[
            ResponsiveUtils.buildResponsiveSection(
              context: context,
              title: 'Available Goals',
              icon: Icons.add_task,
              children: [
                LayoutBuilder(
                  builder: (context, constraints) {
                    final isSmallScreen = constraints.maxWidth < 600;
                    final isMediumScreen = constraints.maxWidth < 900;

                    return Wrap(
                      spacing: ResponsiveUtils.getSpacing(context),
                      runSpacing: ResponsiveUtils.getSpacing(context),
                      children: _availableGoals.map((goal) {
                        final cardWidth = isSmallScreen
                            ? constraints.maxWidth
                            : isMediumScreen
                                ? (constraints.maxWidth - ResponsiveUtils.getSpacing(context)) / 2
                                : (constraints.maxWidth - ResponsiveUtils.getSpacing(context) * 2) / 3;

                                                 return Container(
                           width: cardWidth,
                           height: 200, // Reduced height since we removed description
                          padding: EdgeInsets.all(ResponsiveUtils.getSpacing(context)),
                          decoration: BoxDecoration(
                            color: const Color(0xFF1A1A1A),
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(color: const Color(0xFF333333)),
                            boxShadow: [
                              BoxShadow(
                                color: AppTheme.primaryColor.withOpacity(0.1),
                                blurRadius: 8,
                                offset: const Offset(0, 2),
                              ),
                            ],
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                children: [
                                  Container(
                                    padding: const EdgeInsets.all(8),
                                    decoration: BoxDecoration(
                                      color: AppTheme.primaryColor.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    child: Icon(
                                      Icons.flag,
                                      color: AppTheme.primaryColor,
                                      size: ResponsiveUtils.getSmallIconSize(context),
                                    ),
                                  ),
                                  SizedBox(width: ResponsiveUtils.getSpacing(context)),
                                  Expanded(
                                    child: Text(
                                      goal.title,
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: ResponsiveUtils.getSubtitleFontSize(context),
                                        fontWeight: FontWeight.bold,
                                      ),
                                      maxLines: 2,
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ),
                                ],
                              ),
                                                             SizedBox(height: ResponsiveUtils.getSpacing(context)),
                              SizedBox(height: ResponsiveUtils.getSpacing(context)),
                              Row(
                                children: [
                                  Container(
                                    padding: EdgeInsets.symmetric(
                                      horizontal: ResponsiveUtils.getSpacing(context) / 2,
                                      vertical: ResponsiveUtils.getSpacing(context) / 3,
                                    ),
                                    decoration: BoxDecoration(
                                      color: _getPriorityColor(goal.priority).withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        Icon(
                                          Icons.flag,
                                          color: _getPriorityColor(goal.priority),
                                          size: ResponsiveUtils.getSmallIconSize(context),
                                        ),
                                        SizedBox(width: ResponsiveUtils.getSpacing(context) / 2),
                                        Text(
                                          goal.priority,
                                          style: TextStyle(
                                            color: _getPriorityColor(goal.priority),
                                            fontSize: ResponsiveUtils.getSmallFontSize(context),
                                            fontWeight: FontWeight.w600,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const Spacer(),
                                  ElevatedButton.icon(
                                    onPressed: () => _optInForGoal(goal),
                                    icon: Icon(
                                      Icons.add_task,
                                      size: ResponsiveUtils.getSmallIconSize(context),
                                    ),
                                    label: const Text('Opt In'),
                                    style: ElevatedButton.styleFrom(
                                      backgroundColor: AppTheme.primaryColor,
                                      foregroundColor: Colors.white,
                                      padding: EdgeInsets.symmetric(
                                        horizontal: ResponsiveUtils.getSpacing(context),
                                        vertical: ResponsiveUtils.getSpacing(context) / 2,
                                      ),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        );
                      }).toList(),
                    );
                  },
                ),
              ],
            ),
            SizedBox(height: ResponsiveUtils.getSectionSpacing(context)),
          ],

          // My Goals list
          _buildGoalsList(filteredGoals),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: EdgeInsets.all(ResponsiveUtils.getSpacing(context)),
      decoration: BoxDecoration(
        color: const Color(0xFF1A1A1A),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFF333333)),
      ),
      child: Row(
      children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: AppTheme.primaryColor.withOpacity(0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(
              Icons.flag,
              color: AppTheme.primaryColor,
              size: ResponsiveUtils.getIconSize(context),
            ),
          ),
          SizedBox(width: ResponsiveUtils.getSpacing(context)),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'My Goals',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: ResponsiveUtils.getTitleFontSize(context),
                  fontWeight: FontWeight.bold,
                ),
              ),
              SizedBox(height: ResponsiveUtils.getSpacing(context) / 2),
              Text(
                'Track your progress and achievements',
                style: TextStyle(
                  color: AppTheme.textSecondary,
                  fontSize: ResponsiveUtils.getBodyFontSize(context),
                ),
              ),
            ],
          ),
        ),
          if (_availableGoals.isNotEmpty)
          Container(
              padding: EdgeInsets.all(ResponsiveUtils.getSpacing(context) / 2),
            decoration: BoxDecoration(
                color: AppTheme.warningColor.withOpacity(0.1),
              borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(
                    Icons.notifications_active,
                    color: AppTheme.warningColor,
                    size: ResponsiveUtils.getSmallIconSize(context),
                  ),
                  SizedBox(width: ResponsiveUtils.getSpacing(context) / 2),
                  Text(
                    '${_availableGoals.length} goals available',
                    style: TextStyle(
                      color: AppTheme.warningColor,
                      fontSize: ResponsiveUtils.getSmallFontSize(context),
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ],
            ),
          ),
      ],
      ),
    );
  }

  Widget _buildStatsRow() {
    final goalStats = _getGoalStats();
    final stats = [
      {'label': 'In Progress', 'value': '${goalStats['In Progress']}', 'color': AppTheme.primaryColor},
      {'label': 'Completed', 'value': '${goalStats['Completed']}', 'color': AppTheme.successColor},
      {'label': 'Overdue', 'value': '${goalStats['Overdue']}', 'color': AppTheme.errorColor},
      {'label': 'Avg Progress', 'value': '${goalStats['Average Progress']}%', 'color': AppTheme.warningColor},
    ];

    return ResponsiveUtils.buildResponsiveSection(
      context: context,
      title: 'Goal Statistics',
      icon: Icons.analytics,
      children: [
        LayoutBuilder(
          builder: (context, constraints) {
            final isSmallScreen = constraints.maxWidth < 600;
            final isMediumScreen = constraints.maxWidth < 900;

            return Wrap(
              spacing: ResponsiveUtils.getSpacing(context),
              runSpacing: ResponsiveUtils.getSpacing(context),
              children: stats.map((stat) {
                final cardWidth = isSmallScreen
                    ? constraints.maxWidth / 2 - ResponsiveUtils.getSpacing(context)
                    : isMediumScreen
                        ? constraints.maxWidth / 3 - ResponsiveUtils.getSpacing(context)
                        : constraints.maxWidth / 4 - ResponsiveUtils.getSpacing(context);

            return Container(
                  width: cardWidth,
              padding: EdgeInsets.all(ResponsiveUtils.getSpacing(context)),
              decoration: BoxDecoration(
                color: const Color(0xFF1A1A1A),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: const Color(0xFF333333)),
                    boxShadow: [
                      BoxShadow(
                        color: (stat['color'] as Color).withOpacity(0.1),
                        blurRadius: 8,
                        offset: const Offset(0, 2),
                      ),
                    ],
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Container(
                        width: 4,
                        height: 40,
                        decoration: BoxDecoration(
                          color: stat['color'] as Color,
                          borderRadius: BorderRadius.circular(2),
                        ),
                      ),
                      SizedBox(width: ResponsiveUtils.getSpacing(context)),
                      Expanded(
              child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    stat['value'] as String,
                    style: TextStyle(
                      color: stat['color'] as Color,
                      fontSize: ResponsiveUtils.getTitleFontSize(context),
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                            SizedBox(height: ResponsiveUtils.getSpacing(context) / 4),
                  Text(
                    stat['label'] as String,
                    style: TextStyle(
                      color: AppTheme.textSecondary,
                      fontSize: ResponsiveUtils.getSmallFontSize(context),
                    ),
                            ),
                          ],
                        ),
                  ),
                ],
              ),
                );
              }).toList(),
            );
          },
        ),
      ],
    );
  }

  Widget _buildFilterSection() {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isSmallScreen = constraints.maxWidth < 600;

        return Container(
          padding: EdgeInsets.all(ResponsiveUtils.getSpacing(context)),
          decoration: BoxDecoration(
            color: const Color(0xFF1A1A1A),
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: const Color(0xFF333333)),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Row(
      children: [
        Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Filter Goals',
                          style: TextStyle(
                            color: AppTheme.textSecondary,
                            fontSize: ResponsiveUtils.getSmallFontSize(context),
                          ),
                        ),
                        SizedBox(height: ResponsiveUtils.getSpacing(context) / 2),
                        Container(
                          padding: EdgeInsets.symmetric(
                            horizontal: ResponsiveUtils.getSpacing(context),
                            vertical: ResponsiveUtils.getSpacing(context) / 2,
                          ),
            decoration: BoxDecoration(
              color: const Color(0xFF2A2A2A),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: const Color(0xFF333333)),
            ),
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                value: _selectedFilter,
                              isExpanded: true,
                dropdownColor: const Color(0xFF2A2A2A),
                style: TextStyle(
                  color: Colors.white,
                  fontSize: ResponsiveUtils.getBodyFontSize(context),
                ),
                icon: Icon(
                  Icons.arrow_drop_down,
                  color: AppTheme.textSecondary,
                  size: ResponsiveUtils.getSmallIconSize(context),
                ),
                items: _filters.map((String filter) {
                  return DropdownMenuItem<String>(
                    value: filter,
                    child: Text(filter),
                  );
                }).toList(),
                onChanged: (String? newValue) {
                  setState(() {
                    _selectedFilter = newValue!;
                  });
                },
              ),
            ),
          ),
                      ],
        ),
                  ),
                  if (!isSmallScreen) ...[
          SizedBox(width: ResponsiveUtils.getSpacing(context)),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Sort By',
                          style: TextStyle(
                            color: AppTheme.textSecondary,
                            fontSize: ResponsiveUtils.getSmallFontSize(context),
                          ),
                        ),
                        SizedBox(height: ResponsiveUtils.getSpacing(context) / 2),
                        Container(
                          padding: EdgeInsets.symmetric(
                            horizontal: ResponsiveUtils.getSpacing(context),
                            vertical: ResponsiveUtils.getSpacing(context) / 2,
                          ),
                          decoration: BoxDecoration(
                            color: const Color(0xFF2A2A2A),
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(color: const Color(0xFF333333)),
                          ),
                          child: DropdownButtonHideUnderline(
                            child: DropdownButton<String>(
                              value: 'Due Date',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: ResponsiveUtils.getBodyFontSize(context),
                              ),
                              icon: Icon(
                                Icons.arrow_drop_down,
                                color: AppTheme.textSecondary,
                                size: ResponsiveUtils.getSmallIconSize(context),
                              ),
                              items: ['Due Date', 'Priority', 'Progress']
                                  .map((String value) {
                                return DropdownMenuItem<String>(
                                  value: value,
                                  child: Text(value),
                                );
                              }).toList(),
                              onChanged: (String? newValue) {
                                // TODO: Implement sorting
                              },
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ],
              ),
              if (isSmallScreen) ...[
                SizedBox(height: ResponsiveUtils.getSpacing(context)),
                Row(
                  children: [
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Sort By',
                            style: TextStyle(
                              color: AppTheme.textSecondary,
                              fontSize: ResponsiveUtils.getSmallFontSize(context),
                            ),
                          ),
                          SizedBox(height: ResponsiveUtils.getSpacing(context) / 2),
                          Container(
                            padding: EdgeInsets.symmetric(
                              horizontal: ResponsiveUtils.getSpacing(context),
                              vertical: ResponsiveUtils.getSpacing(context) / 2,
                            ),
                            decoration: BoxDecoration(
                              color: const Color(0xFF2A2A2A),
                borderRadius: BorderRadius.circular(8),
                              border: Border.all(color: const Color(0xFF333333)),
                            ),
                            child: DropdownButtonHideUnderline(
                              child: DropdownButton<String>(
                                value: 'Due Date',
                                isExpanded: true,
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: ResponsiveUtils.getBodyFontSize(context),
                                ),
                                icon: Icon(
                                  Icons.arrow_drop_down,
                                  color: AppTheme.textSecondary,
                                  size: ResponsiveUtils.getSmallIconSize(context),
                                ),
                                items: ['Due Date', 'Priority', 'Progress']
                                    .map((String value) {
                                  return DropdownMenuItem<String>(
                                    value: value,
                                    child: Text(value),
                                  );
                                }).toList(),
                                onChanged: (String? newValue) {
                                  // TODO: Implement sorting
                                },
                              ),
            ),
          ),
        ],
                      ),
                    ),
                  ],
                ),
              ],
            ],
          ),
        );
      },
    );
  }

  Widget _buildGoalsList(List<GoalModel> goals) {
    return ResponsiveUtils.buildResponsiveSection(
      context: context,
      title: 'My Goals',
      icon: Icons.flag,
      children: [
        if (goals.isEmpty)
          Center(
            child: Column(
              children: [
                Icon(
                  Icons.flag_outlined,
                  size: ResponsiveUtils.getIconSize(context) * 2,
                  color: AppTheme.textSecondary,
                ),
                SizedBox(height: ResponsiveUtils.getSpacing(context)),
                Text(
                  'No goals found',
                  style: TextStyle(
                    color: AppTheme.textSecondary,
                    fontSize: ResponsiveUtils.getBodyFontSize(context),
                  ),
                ),
              ],
            ),
          )
        else
          Container(
            decoration: BoxDecoration(
              color: const Color(0xFF1A1A1A),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: const Color(0xFF333333)),
            ),
            child: ListView.separated(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: goals.length,
              separatorBuilder: (context, index) => Divider(
                color: const Color(0xFF333333),
                height: 1,
                thickness: 1,
              ),
            itemBuilder: (context, index) {
                return _buildGoalListItem(goals[index]);
            },
            ),
          ),
      ],
    );
  }

    Widget _buildGoalListItem(GoalModel goal) {
    final statusColor = _getStatusColor(goal.status);
    final priorityColor = _getPriorityColor(goal.priority);
    
    return ListTile(
      contentPadding: EdgeInsets.symmetric(
        horizontal: ResponsiveUtils.getSpacing(context),
        vertical: ResponsiveUtils.getSpacing(context) / 2,
      ),
      title: Row(
            children: [
              Expanded(
                child: Text(
              goal.title,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: ResponsiveUtils.getSubtitleFontSize(context),
                    fontWeight: FontWeight.bold,
                  ),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
          SizedBox(width: ResponsiveUtils.getSpacing(context)),
              Container(
                padding: EdgeInsets.symmetric(
                  horizontal: ResponsiveUtils.getSpacing(context) / 2,
                  vertical: ResponsiveUtils.getSpacing(context) / 3,
                ),
                decoration: BoxDecoration(
                  color: statusColor.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
              goal.status,
                  style: TextStyle(
                    color: statusColor,
                    fontSize: ResponsiveUtils.getSmallFontSize(context),
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
      subtitle: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(height: ResponsiveUtils.getSpacing(context)),
          
          // Priority and Due Date
          Row(
            children: [
              Container(
                padding: EdgeInsets.symmetric(
                  horizontal: ResponsiveUtils.getSpacing(context) / 2,
                  vertical: ResponsiveUtils.getSpacing(context) / 3,
                ),
                decoration: BoxDecoration(
                  color: priorityColor.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  goal.priority,
                  style: TextStyle(
                    color: priorityColor,
                    fontSize: ResponsiveUtils.getSmallFontSize(context),
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              const Spacer(),
              Text(
                'Due: ${goal.dueDate.toString().split(' ')[0]}',
                style: TextStyle(
                  color: AppTheme.textSecondary,
                  fontSize: ResponsiveUtils.getSmallFontSize(context),
                ),
              ),
            ],
          ),
          
          SizedBox(height: ResponsiveUtils.getSpacing(context)),
          
          // Progress Section
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
          Text(
                    'Progress',
            style: TextStyle(
              color: AppTheme.textSecondary,
              fontSize: ResponsiveUtils.getSmallFontSize(context),
                    ),
                  ),
                  Row(
                    children: [
                      Text(
                        '${goal.progressPercentage.toStringAsFixed(1)}%',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: ResponsiveUtils.getSmallFontSize(context),
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      SizedBox(width: ResponsiveUtils.getSpacing(context) / 2),
                      IconButton(
                        icon: const Icon(Icons.edit, size: 16),
                        color: AppTheme.primaryColor,
                        onPressed: () => _showUpdateProgressDialog(goal),
                      ),
                    ],
                  ),
                ],
              ),
              SizedBox(height: ResponsiveUtils.getSpacing(context) / 2),
              LinearProgressIndicator(
                value: goal.progressPercentage / 100,
                backgroundColor: const Color(0xFF333333),
                valueColor: AlwaysStoppedAnimation<Color>(statusColor),
              ),
            ],
          ),
        ],
      ),
      onTap: () => _showUpdateProgressDialog(goal),
    );
  }

  Widget _buildGoalCard(GoalModel goal) {
    final statusColor = _getStatusColor(goal.status);
    final priorityColor = _getPriorityColor(goal.priority);
    
    return Container(
      height: 320, // Increased height for better content display
      padding: EdgeInsets.all(ResponsiveUtils.getSpacing(context)),
      decoration: BoxDecoration(
        color: const Color(0xFF1A1A1A),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFF333333)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header with status
          Row(
            children: [
              Expanded(
                child: Text(
                  goal.title,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: ResponsiveUtils.getSubtitleFontSize(context),
                    fontWeight: FontWeight.bold,
            ),
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
                ),
              ),
              Container(
                padding: EdgeInsets.symmetric(
                  horizontal: ResponsiveUtils.getSpacing(context) / 2,
                  vertical: ResponsiveUtils.getSpacing(context) / 3,
                ),
                decoration: BoxDecoration(
                  color: statusColor.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
                  goal.status,
                  style: TextStyle(
                    color: statusColor,
                    fontSize: ResponsiveUtils.getSmallFontSize(context),
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
          
          SizedBox(height: ResponsiveUtils.getSpacing(context)),
          
          // Progress section
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Progress',
                    style: TextStyle(
                      color: AppTheme.textSecondary,
                      fontSize: ResponsiveUtils.getSmallFontSize(context),
                    ),
                  ),
                  Row(
                    children: [
                  Text(
                        '${goal.progressPercentage.toStringAsFixed(1)}%',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: ResponsiveUtils.getSmallFontSize(context),
                      fontWeight: FontWeight.w600,
                    ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.edit, size: 16),
                        color: AppTheme.primaryColor,
                        onPressed: () => _showUpdateProgressDialog(goal),
                      ),
                    ],
                  ),
                ],
              ),
              SizedBox(height: ResponsiveUtils.getSpacing(context) / 2),
              LinearProgressIndicator(
                value: goal.progressPercentage / 100,
                backgroundColor: const Color(0xFF333333),
                valueColor: AlwaysStoppedAnimation<Color>(statusColor),
              ),
            ],
          ),
          
          SizedBox(height: ResponsiveUtils.getSpacing(context)),
          
          // Footer info
          Row(
            children: [
              Container(
                padding: EdgeInsets.symmetric(
                  horizontal: ResponsiveUtils.getSpacing(context) / 2,
                  vertical: ResponsiveUtils.getSpacing(context) / 3,
                ),
                decoration: BoxDecoration(
                  color: priorityColor.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  goal.priority,
                  style: TextStyle(
                    color: priorityColor,
                    fontSize: ResponsiveUtils.getSmallFontSize(context),
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              const Spacer(),
              Text(
                'Due: ${goal.dueDate.toString().split(' ')[0]}',
                style: TextStyle(
                  color: AppTheme.textSecondary,
                  fontSize: ResponsiveUtils.getSmallFontSize(context),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildAvailableGoalCard(GoalModel goal) {
    final priorityColor = _getPriorityColor(goal.priority);
    
    return Container(
      padding: EdgeInsets.all(ResponsiveUtils.getSpacing(context)),
      decoration: BoxDecoration(
        color: const Color(0xFF1A1A1A),
        borderRadius: BorderRadius.circular(ResponsiveUtils.getCardBorderRadius(context)),
        border: Border.all(color: const Color(0xFF333333)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header with title
          Text(
            goal.title,
            style: TextStyle(
              color: Colors.white,
              fontSize: ResponsiveUtils.getSubtitleFontSize(context),
              fontWeight: FontWeight.bold,
            ),
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
          ),
          
          SizedBox(height: ResponsiveUtils.getSpacing(context) / 2),
          
          // Description
          if (goal.description != null) Text(
            goal.description!,
            style: TextStyle(
              color: AppTheme.textSecondary,
              fontSize: ResponsiveUtils.getSmallFontSize(context),
            ),
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
          ),
          
          const Spacer(),
          
          // Footer info
          Row(
            children: [
              Container(
                padding: EdgeInsets.symmetric(
                  horizontal: ResponsiveUtils.getSpacing(context) / 2,
                  vertical: ResponsiveUtils.getSpacing(context) / 3,
                ),
                decoration: BoxDecoration(
                  color: priorityColor.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  goal.priority,
                  style: TextStyle(
                    color: priorityColor,
                    fontSize: ResponsiveUtils.getSmallFontSize(context),
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              const Spacer(),
              ElevatedButton(
                onPressed: () => _optInForGoal(goal),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.primaryColor,
                  foregroundColor: Colors.white,
                  padding: ResponsiveUtils.getButtonPadding(context),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                child: const Text('Participate'),
              ),
            ],
          ),
        ],
      ),
    );
  }

  void _showUpdateProgressDialog(GoalModel goal) {
    double newProgress = goal.progressPercentage;
    String newStatus = goal.status;

    showDialog(
      context: context,
      barrierColor: Colors.black.withOpacity(0.5),
      builder: (dialogContext) => StatefulBuilder(
        builder: (context, setDialogState) => Dialog(
          insetPadding: EdgeInsets.symmetric(
            horizontal: MediaQuery.of(context).size.width > 900 
              ? MediaQuery.of(context).size.width * 0.3 
              : 24,
            vertical: 24,
          ),
          backgroundColor: const Color(0xFF1A1A1A),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
            side: const BorderSide(color: Color(0xFF333333)),
          ),
                     child: Container(
             padding: const EdgeInsets.all(24),
             child: Column(
               mainAxisSize: MainAxisSize.min,
               crossAxisAlignment: CrossAxisAlignment.start,
               children: [
                 Text(
                   'Update Goal Progress',
                   style: TextStyle(
                     color: Colors.white,
                     fontSize: ResponsiveUtils.getTitleFontSize(context),
                     fontWeight: FontWeight.bold,
                   ),
                 ),
                 const SizedBox(height: 16),
                 
                 // Goal Title
                 Text(
                   goal.title,
                   style: TextStyle(
                     color: AppTheme.primaryColor,
                     fontSize: ResponsiveUtils.getSubtitleFontSize(context),
                     fontWeight: FontWeight.w600,
                   ),
                 ),
                 
                 // Goal Description
                 if (goal.description != null) ...[
                   const SizedBox(height: 8),
                   Text(
                     goal.description!,
                     style: TextStyle(
                       color: AppTheme.textSecondary,
                       fontSize: ResponsiveUtils.getSmallFontSize(context),
                     ),
                   ),
                 ],
                 
                 const SizedBox(height: 24),
                
                // Progress Section
                Text(
                  'Progress',
                  style: TextStyle(
                    color: AppTheme.textSecondary,
                    fontSize: ResponsiveUtils.getSmallFontSize(context),
                  ),
                ),
                const SizedBox(height: 8),
                Row(
                  children: [
                    Expanded(
                      child: SliderTheme(
                        data: SliderThemeData(
                          activeTrackColor: AppTheme.primaryColor,
                          inactiveTrackColor: const Color(0xFF333333),
                          thumbColor: AppTheme.primaryColor,
                          overlayColor: AppTheme.primaryColor.withOpacity(0.2),
                          trackHeight: 4,
                        ),
                        child: Slider(
                          value: newProgress,
                          min: 0,
                          max: 100,
                          divisions: 100,
                          label: '${newProgress.round()}%',
                          onChanged: (value) {
                            setDialogState(() => newProgress = value);
                          },
                        ),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                      decoration: BoxDecoration(
                        color: const Color(0xFF2A2A2A),
                        borderRadius: BorderRadius.circular(4),
                      ),
                      child: Text(
                        '${newProgress.round()}%',
                        style: const TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),

                // Status Section
                Text(
                  'Status',
                  style: TextStyle(
                    color: AppTheme.textSecondary,
                    fontSize: ResponsiveUtils.getSmallFontSize(context),
                  ),
                ),
                const SizedBox(height: 8),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                  decoration: BoxDecoration(
                    color: const Color(0xFF2A2A2A),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: const Color(0xFF333333)),
                  ),
                  child: DropdownButtonHideUnderline(
                    child: DropdownButton<String>(
                      value: newStatus,
                      isExpanded: true,
                      dropdownColor: const Color(0xFF2A2A2A),
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 16,
                      ),
                      icon: Icon(
                        Icons.arrow_drop_down,
                        color: AppTheme.textSecondary,
                      ),
                      items: ['Not Started', 'In Progress', 'Completed']
                          .map((status) => DropdownMenuItem(
                                value: status,
                                child: Text(status),
                              ))
                          .toList(),
                      onChanged: (value) {
                        if (value != null) {
                          setDialogState(() => newStatus = value);
                        }
                      },
                    ),
                  ),
                ),
                const SizedBox(height: 32),

                // Action Buttons
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    TextButton(
                      onPressed: () => Navigator.pop(context),
                      style: TextButton.styleFrom(
                        foregroundColor: AppTheme.textSecondary,
                      ),
                      child: const Text('Cancel'),
                    ),
                    const SizedBox(width: 16),
                    ElevatedButton(
                      onPressed: () {
                        if (newStatus == 'Completed' && newProgress < 100) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(
                              content: const Text('Progress must be 100% to mark goal as completed'),
                              backgroundColor: AppTheme.errorColor,
                              behavior: SnackBarBehavior.floating,
                            ),
                          );
                          return;
                        }
                        Navigator.pop(context);
                        _updateGoalProgress(goal, newProgress, newStatus);
                      },
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppTheme.primaryColor,
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                      child: const Text('Update'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  List<GoalModel> _getFilteredGoals() {
    if (_selectedFilter == 'All') {
      return _goals;
    }
    return _goals.where((goal) => goal.status == _selectedFilter).toList();
  }

  Map<String, dynamic> _getGoalStats() {
    int notStarted = 0;
    int inProgress = 0;
    int completed = 0;
    int overdue = 0;
    double totalProgress = 0;

    for (var goal in _goals) {
      if (goal.isOverdue) {
        overdue++;
      }
      
      switch (goal.status) {
        case 'Not Started':
          notStarted++;
          break;
        case 'In Progress':
          inProgress++;
          break;
        case 'Completed':
          completed++;
          break;
      }

      totalProgress += goal.progressPercentage;
    }

    return {
      'Not Started': notStarted,
      'In Progress': inProgress,
      'Completed': completed,
      'Overdue': overdue,
      'Average Progress': _goals.isEmpty ? 0 : (totalProgress / _goals.length).round(),
    };
  }

  Color _getStatusColor(String status) {
    switch (status.toLowerCase()) {
      case 'not started':
        return AppTheme.textSecondary;
      case 'in progress':
        return AppTheme.primaryColor;
      case 'completed':
        return AppTheme.successColor;
      case 'overdue':
        return AppTheme.errorColor;
      default:
        return AppTheme.textSecondary;
    }
  }

  Color _getPriorityColor(String priority) {
    switch (priority.toLowerCase()) {
      case 'high':
        return AppTheme.errorColor;
      case 'medium':
        return AppTheme.warningColor;
      case 'low':
        return AppTheme.successColor;
      default:
        return AppTheme.textSecondary;
    }
  }
} 